### ISSUE TITLE
Mobile Meta

### ISSUE THREAD

**Issue by Mikeysax** [ansonmela/splurty_firehose#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by ansonmela** [comment]
So I looked it up on google and added this line to application.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

Mobile looks good now!

**Comment by ansonmela** [comment]
`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">`

**Comment by Mikeysax** [comment]
:+1:
